dev:
	flutter run

watch:
	flutter pub run build_runner watch --delete-conflicting-outputs

build_runner:
	flutter pub run build_runner build --delete-conflicting-outputs

clean_build:
	flutter clean
	flutter pub get
	flutter run

clean:
	flutter clean