name: calorie_go_flutter
description: A new Flutter project with Serverpod.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.0.1
  calorie_go_client:
    path: ../calorie_go_client

  cupertino_icons: ^1.0.6
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  dio: ^5.5.0
  serverpod_auth_shared_flutter: ^2.0.1
  serverpod_auth_google_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
