version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /calorie_go_server/
    destination: /home/ec2-user/serverpod/upload/calorie_go_server/
hooks:
  BeforeInstall:
    - location: calorie_go_server/deploy/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: calorie_go_server/deploy/aws/scripts/start_server
      timeout: 300
      runas: root
