name: flutter-ci

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'calorie_go_flutter/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
      - name: Go to mobile directory
        run: cd calorie_go_flutter
      - name: Install dependencies
        run: flutter pub get
      - name: generate files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: analyze
        run: flutter analyze
